### ISSUE TITLE
Breaks the file in React Native 0.46

### ISSUE THREAD

**Issue by Vlad-Zhukov** [jhen0409/remote-redux-devtools-on-debugger#23]
Thanks for the tool, it's very useful! However in `react-native@0.46` it looks like it injects the server in the wrong place and breaks the file.

**Comment by jhen0409** [comment]
We can waiting for https://github.com/zalmoxisus/remotedev-server/pull/40 got merge and release.

**Comment by jhen0409** [comment]
Fixed in the new patch version of `remotedev-server` (v0.2.3).

**Comment by fhad-getmaple** [comment]
Still getting this issue even after upgrading remotedev-server (v0.2.3)

**Comment by jhen0409** [comment]
@fhad-getmaple I've tested with initial project, it works fine for me.

```bash
react-native init Test047
cd Test047
npm install --save-dev remotedev-rn-debugger
$(npm bin)/remotedev-debugger --injectserver
react-native start
```

You can try to reinstall dependencies.
